create_clock -period 8.000 -name Clk125 [get_ports Clk125M]
#set_false_path -from [get_ports sys_rst_n]

#set_property PACKAGE_PIN B10 [get_ports sys_rst_n]
#set_property PULLUP true [get_ports sys_rst_n]

#set_property PACKAGE_PIN E7 [get_ports Clk_33_333MHz]
set_property PACKAGE_PIN P20 [get_ports TX]
set_property PACKAGE_PIN T19 [get_ports RX]
set_property PACKAGE_PIN N20 [get_ports Clk14]
set_property PACKAGE_PIN H16 [get_ports Clk125M]
set_property PACKAGE_PIN U15 [get_ports Rst_n]

#set_property IOSTANDARD LVCMOS33 [get_ports Clk_33_333MHz]
#set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property IOSTANDARD LVCMOS33 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports Clk14]
set_property IOSTANDARD LVCMOS33 [get_ports Clk125M]
set_property IOSTANDARD LVCMOS33 [get_ports Rst_n]